project:
  type: website
  output-dir: docs
  

website:
  title: "Luc Clair"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: Research.qmd
        text: "{{< fa book >}} Research"
      - text: "{{< fa chalkboard-user >}} Teaching"
        menu:
          - text: Overview
            href: Teaching.qmd 
          - text: Teaching Philosophy
            href: philosophy.qmd
    right:
      - href: github.com
        icon: github
      - href: https://twitter.com/Luc_Clair
        icon: twitter


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

